### ISSUE TITLE
Component/Schema and Reference Support

### ISSUE THREAD

**Issue by arnonym** [sukovanej/schema-openapi#130]
Hi Milan,

I played a bit with your effect http server implementation and schema-openapi projects and missed component schema and reference generation for schemas using identifiers, so I implemented that as an exercise. I also added support for lazy/recursive schemas:

https://github.com/sukovanej/schema-openapi/compare/master...arnonym:schema-openapi:master
https://github.com/sukovanej/effect-http/compare/master...arnonym:effect-http:master

What do you think? Would it make sense to explore that further or does that not match the direction you would like to go with this project?

Arne

**Comment by sukovanej** [comment]
Hey, love that! Definitely, let's explore what's possible there. 

In the past, I already thought about components because of an internal service I work on where we have lots of data structures used on multiple places or the same structure is used also in an array or as a part of another object.

I'll check the changes into more details, it looks very promising!

**Comment by arnonym** [comment]
Nice to hear that! I've created 2 PRs on the repositories, so we can work from there. Let's discuss changes and ideas!
